### PR TITLE
faster variant of index.addPath() and async constructor for ZipFS

### PR DESCRIPTION
**Pull request by hrj**
* A new variant of `addPath()` has been added, called `addPathFast()`. The main difference is that it uses `string.lastIndexOf(/)` to derive the basename and filename from the path. Whereas the original version uses `path.dirname()` which is slow, because it does more.

* The constructor for ZipFS now accepts an index that has been already computed. A new method for creating this index has been added, called `computeIndex()`. This method yields the thread frequently and invokes a callback when done, with the index as the parameter.

@jvilk's proposal to the constructor API is slightly different than mine: passing a boolean to indicate async construction along with a call-back. However I think that is more error prone to use, since the object returned by the constructor is immediately available to the user although they are not supposed to use it immediately.

In the API as present in this PR, the object returned by the constructor is safe to use, because the index is computed by the user before the constructor is invoked. This is how the usage would look like:

```
ZipFS.computeIndex(data, (index) => {
  const fs = new ZipFS(index, 'name');
  // fs is ready to be used here
});
```

@jvilk I am fairly new to the library and this is just my humble opinion. I can change the API to match your proposal if you still think that is better.

### CODE REVIEW

**Comment by hrj** [comment]
Forgot to mention: The other advantage with the API in this PR is that it matches the API style of XHRFS.

**Comment by jvilk** [comment]
After thinking about this, I am OK with this design!

I have some further comments that should be addressed before I can merge this in. Fortunately, I do not think they will take long. :)

* A unit test for ZipFS only that tests this new option (like w/ XHRFS).
* Removal of duplicated code.
  * `populateIndex()` should use `addToIndex()`
  * While I'm not 100% happy at duplicated index population loops, I don't see a better option. (And their logic is simple enough to forgive duplicating.)
* Is `computeIndexResponsive` supposed to be public? Looks like a private helper method.

**Comment by hrj** [comment]
Thanks for reviewing! I have updated the PR:
* Added unit test. (It gets executed thrice; not sure why! I guess the harness creates multiple scenarios for the 3 different fixtures in `test/fixtures/zipfs/`. Is that so, and how do I use the scenario parameter?) 
* Agreed, used `addToIndex()` in `popluateIndex()`
* No it was not supposed to be public, fixed.

**Comment by jvilk** [comment]
> I guess the harness creates multiple scenarios for the 3 different fixtures in test/fixtures/zipfs/. Is that so, and how do I use the scenario parameter?

Oh crap, right! You actually should just simply use one of those fixtures to construct one of these ZipFS objects instead of writing a custom test. I'm sorry; I forgot about that.

You should modify the ZipFS factory to construct a ZipFS object with this index:

https://github.com/jvilk/BrowserFS/blob/master/test/harness/factories/zipfs_factory.ts

Use just one fixture: either 4 or 9, since 0 is just a zip with `STORE`'d files.

Then, *all* of the ZipFS tests will be run on that object, and you can eliminate the backend-specific test unless there's 

Sorry for the misdirection!

**Comment by hrj** [comment]
> Use just one fixture: either 4 or 9, since 0 is just a zip with STORE'd files.
> Then, all of the ZipFS tests will be run on that object, and you can eliminate the backend-specific test.

No worries; done!

It's late here; in case you merge this in, please consider publishing a new npm release. I can then make a PR to doppio to use this async feature.

**Comment by jvilk** [comment]
Merged! I'll add a reminder to make a new release tonight.

**Comment by jvilk** [comment]
@hrj this is now in the latest release.

**Comment by hrj** [comment]
@jvilk Nice. I also saw that you updated the dependencies. Thanks * 2!

**Pull request merged**
