### PR TITLE
Proxy FS

### LINKED ISSUE #196: New backend proposal: ProxyFS
I just had this idea as a way to implement the file-system watcher described in https://github.com/jvilk/BrowserFS/issues/163

We could have a backend that wrapped another file system and provided hooks so you could intercept any of the method calls and add additional logic. In this scenario, I would simply intercept write, mkdir, rmdir, rename, and unlink to easily create my own "file system watcher".

ProxyFS is meant to allude to JS Proxy objects, but other names I came up with first included HookFS, WatchFS, SpyFS, or InterceptorFS.

### PR DESCRIPTION
**Pull request by wmhilton**
or Middleware FS. or Hook FS. Or Instrument FS? I can be indecisive. Fixes #196

The goal is a backend that will proxy (wrap) any existing backend, while letting you the user hook into some of the internals. This will make it trivial to implement file-system "watching" behavior. Currently I'm planning these hooks:

- before/after read
- before/after write
- before/after create
- before/after delete
- before/after mkdir
- before/after rmdir

I am also contemplating whether or not to add *transform* hooks. These would allow modifying the behavior of a file system by letting you transform the arguments and results. This is a much trickier feature. Having transform hooks would enable rapidly prototyping filesystems in user-space, with whatever pros and cons that brings. (Think of FUSE in Linux)

### CODE REVIEW

**Comment by wmhilton** [comment]
DON'T MERGE IT YET!!!

Feedback on how to achieve my goals with less typing would be appreciated. I tried some simpler ways than what I'm doing, but I couldn't get the type checker to like them.

**Comment by wmhilton** [comment]
Currently I have only wrapped `readFileSync` and `writeFileSync`. However I did make a lovely factory to test that all the pass-through functionality works.

**Comment by emeryberger** [comment]
Looks like this should be closed, correct?

**Comment by emeryberger** [comment]
I'm going to close this since it's been idle for years. Please feel free to post a comment and I can always re-open it.

**Pull request closed without merging**
