### PR TITLE
Build browserfs.js with Browserify

### PR DESCRIPTION
**Pull request by timdream**
This is currently broken because of lack of mikefrey/grunt-exorcise#12. I've also found that running `grunt` alone will no longer get bower package installed.

I've verified this patch works by executing the following commands

```
npm i
./node_modules/.bin/bower install
cd ./node_modules/grunt-exorcise/ && npm i -D exorcist@0.4 && cd -
grunt
```

The generated file is slightly smaller unminified but a bit larger minified.

```
$ ls -l dist/
-rw-r--r--  1 timdream  staff  450334 May 24 00:55 browserfs.js
-rw-r--r--  1 timdream  staff  512053 May 24 00:55 browserfs.js.map
-rw-r--r--  1 timdream  staff  138016 May 24 00:55 browserfs.min.js
-rw-r--r--  1 timdream  staff  587035 May 24 00:55 browserfs.min.js.map

$ ls -l build/release/
-rw-r--r--  1 timdream  staff  448613 May 29 18:14 browserfs.js
-rw-r--r--  1 timdream  staff  519373 May 29 18:14 browserfs.js.map
-rw-r--r--  1 timdream  staff  150666 May 29 18:14 browserfs.min.js
-rw-r--r--  1 timdream  staff  719307 May 29 18:14 browserfs.min.js.map
```

But hey, they are UMD'd so this solves #107.

As of the source maps, they still points to the JavaScript files generated from TypeScript just like the current sourece map. There are set-ups out there claiming we should be able to map directly into `.ts` file, but I haven't try it. Probably can be done in another follow-up pull request.

The remaining issue to work on this pull request is to ensure karma still runs. I am so far unable to make it work on my machine (w/ or w/o the patch) so I can't verify that, yet.

### CODE REVIEW

**Comment by timdream** [comment]
karma now magics work for the second time when I tried. It shows errors because obviously the harness needs to be fixed.

**Comment by jvilk** [comment]
Awesome work! I'll take a look at this when I get home from work; looks like a nice, clean change. Are you thinking of tackling the (somewhat intense) harness, or are you leaving that to me?

**Comment by timdream** [comment]
> Are you thinking of tackling the (somewhat intense) harness, or are you leaving that to me?

I could do it but it would take some time; you can do it if you can't wait :)

**Comment by timdream** [comment]
A new commit attached and verified `grunt test` works.

I realized all the tests are written in AMD and are being loaded by karma without any transform. I am reluctant to invest more time figuring out how to convert these tests from AMD nor do manual conversion of all tests, so I am restoring how require.js is used in tests.

This pull request now introduce browserify, remove r.js (the require.js propressor) but did not remove require.js. I wonder if we are complicating things too much...

**Comment by jvilk** [comment]
I am willing to rewrite the unit tests back to their original CommonJS form if it's possible to lazily load them using browserify. Is that possible?

**Comment by jvilk** [comment]
From a cursory look at browserify, it looks like they always expect you to bundle.

**Comment by jvilk** [comment]
Yup:

http://stackoverflow.com/questions/24833367/can-you-use-browserify-without-bundling

Hm. That's annoying.

**Comment by wjordan** [comment]
Thanks again for looking into the possibility of supporting Browserify with this library, I'm following the progress on this with great interest!

i don't know specifically why you need to lazy-load the test suite (perhaps it's very large and would otherwise be a long bundle time for running a single test?), but the package usually recommended for lazy-loading within browserify is [partition-bundle](https://github.com/arian/partition-bundle), so that would be something to check out and see if it's good enough for this part.

Let me know if you have any other Q's about how browserify might possibly work for this kind of a refactor, I'll try to offer any help I can!

**Comment by jvilk** [comment]
Hey @wjordan! Lazy loading isn't necessarily required, I just figured it would be a PITA to change it. Maybe not, though. The test suite isn't too big; it's a modified version of the Node test suite for the fs/path/buffer interfaces.

Are you suggesting that I could e.g. partition the tests into their own JS, which could load the BrowserFS library via partition-bundle?

**Comment by jvilk** [comment]
Perhaps I will experiment with [karma-browserify](https://github.com/nikku/karma-browserify) in a bit... I'm currently working on some features in a branch I'd like to complete before EOD.

**Comment by jvilk** [comment]
As an aside, if we get the tests working as CommonJS modules, we could dogfood using BrowserFS for `fs` as suggested in #110. Right now, the test harness hackily makes `fs` and `path` globals.

**Comment by timdream** [comment]
I was looking at `karma-browserify` too before I stop. Supposedly it should be able to create for the test runner to run.

**Comment by jvilk** [comment]
I merged this into a branch here:

https://github.com/jvilk/BrowserFS/pull/112

Now that I completed those features I mentioned a week ago, I'll take a look at this...

**Comment by timdream** [comment]
Closing.

**Pull request closed without merging**
